# 収集対象のキーワード設定
ml_keywords:
  - machine learning
  - LLM
  - graph neural network
  - materials informatics

chem_keywords:
  - chemistry
  - polymer
  - corrosion
  - MOF
  - organic chemistry
  - interfacial chemistry
  - polymer science
  - electrochemistry
  - coating
  - electrodeposition

max_results: 60          # 各ソースの最大取得件数（上限）
lookback_hours: 30       # 直近何時間を対象にするか（9時実行で前日分を拾いやすい設定）
min_items_to_email: 1    # これ未満なら送信スキップ（0で必ず送信）
